# -*- coding: utf-8 -*-
"""week3.鄧皓謙.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GGLkF-TOouu0bBSBtRSVgQSec6wY1Js7
"""

print("Hello World")

print("我是鄧皓謙")

