# -*- coding: utf-8 -*-
"""week4.鄧皓謙.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GGLkF-TOouu0bBSBtRSVgQSec6wY1Js7
"""

a=int(input("第一次期中考成績"))
b=int(input("第二次期中考成績"))
c=int(input("期末考成績"))
print(a+b+c)
print((a+b+c)/3)

d=int(input("請輸入幾尺"))
print(d,"尺")
e=int(input("請輸入幾吋"))
print(e,"吋")
(d*12+e)*2.54

