# -*- coding: utf-8 -*-
"""week67.鄧皓謙.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GGLkF-TOouu0bBSBtRSVgQSec6wY1Js7
"""

player = "Ron Harper"
player_list = ["Ron Harper", "Michael Jordan", "Scottie Pippen", "Dennis Rodman", "LucLongley"]
player_tuple = tuple(player_list)
player_dict = {
"PG": "Ron Harper",
"SG": "Michael Jordan",
"SF": "Scottie Pippen",
"PF": "Dennis Rodman",
"C": "Luc Longley"
}
player_set = set(player_list)
print(type(player))
print(type(player_list))
print(type(player_tuple))
print(type(player_dict))
print(type(player_set))

s1 = '春眠不覺曉,處處聞啼鳥。' 
print(s1)

s2 = "夜來風雨聲,花落知多少。"
print(s2)

s3 = '作者"孟浩然" 詩名"春曉"' 
print(s3)
s4 = "作者'孟浩然' 詩名'春曉'" 
print(s4)

s5 = ''' 春眠不覺曉,處處聞啼鳥。
夜來風雨聲,花落知多少。
作者"孟浩然" 詩名"春曉"
'''
print(s5)

s1 ="123"
s2 = "456"
s3 = s1 + s2 
print(s3)

s4 = s1 * 2 
print(s4)

s5 = '春眠不覺曉,處處聞啼鳥。\n\
夜來風雨聲,花落知多少。\n\
\t作者"孟浩然" 詩名"春曉"' #空八格(tab)
print(s5)

s = '0123456789'
print(s[0])
print('s[1]=', s[1])
print(s[-1])
print('s[-2]=', s[-2])

s = '0123456789'
print('s=', s, 's[:]=', s[:])
print('s=', s, 's[5:]=', s[5:])
print('s=', s, 's[-2:]=', s[-2:])
print('s=', s, 's[:5]=', s[:5])
print('s=', s, 's[:-2]=', s[:-2])
print('s=', s, 's[7:9]=', s[7:9])
print('s=', s, 's[-4:-1]=', s[-4:-1])
print('s=', s, 's[5:-2]=', s[5:-2])
print('s=', s, 's[2:10:2]=', s[2:10:2])
print('s=', s, 's[::-1]=', s[::-1])
print('s=', s, 's[-1::-1]=', s[-1::-1])

s = '春眠不覺曉,處處聞啼鳥,夜來風雨聲,花落知多少。'
print(len(s))

s = '春眠不覺曉,處處聞啼鳥,夜來風雨聲,花落知多少。'
list1 = s.split(',')
print(list1)

list1 = ['春眠不覺曉','處處聞啼鳥','夜來風雨聲','花落知多少。']
s2=','.join(list1)
print(s2)

s1='春眠不覺曉,處處聞啼鳥,夜來風雨聲,花落知多少。'
print(s1.count('處'))

s1='春眠不覺曉,處處聞啼鳥,夜來風雨聲,花落知多少。'
s3=s1.replace('春','冬')
print(s3)

s1='An apple a day.'
print(s1.capitalize())

s1='An apple a day.'
print(s1.title())

s1='An apple a day.'
print(s1.swapcase())

s1='An apple a day.'
print(s1.lower())

t1 = ()
print(t1)
t2 = ('z', )
print(t2)
t3 = (1, 2, 3)
print(t3)
t4 = (1,2,3,4)
t5 = (t4,5,6)
print(t5)

list1=[1,2,3,4]
t6 = tuple(list1)
print(t6)

t1= (1,2,3,4)
t2 = (5,6,t2)
print(len(t2))
print(t2[0])
print(t2[2][0])

shoplist = ['牛奶', '蛋', '咖啡豆', '西瓜', '鳳梨']
print('購物清單shoplist為')
print(shoplist)
listm = [1, 2.0, 'Python']
print("串列可以包含各種資料型別的元素")
print(listm)

tuple2 = ('a', 'b', 1, 2)
list2 = list(tuple2)
print(list2)

shoplist1 = ['牛奶', '蛋', '咖啡豆']
shoplist2 = ['西瓜', '鳳梨']
shoplist_all = shoplist1 + shoplist2
print(shoplist_all)

shoplist = ['牛奶', '蛋', '咖啡豆', '西瓜', '鳳梨']
print('顯示shoplist[0]為',shoplist[0])

shoplist = ['牛奶', '蛋', '咖啡豆', '西瓜', '鳳梨']
index = shoplist.index('咖啡豆')
print("執行 index = shoplist.index('咖啡豆') 後")
print('index=', index)

shoplist = ['牛奶', '蛋', '咖啡豆', '西瓜', '鳳梨']
shoplist[1] = '皮蛋'
print("執行 shoplist[1] = '皮蛋' 後")
print(shoplist)

shoplist = ['牛奶', '蛋', '咖啡豆', '西瓜', '鳳梨']
a = list('abcdefghijk')
print('a[:]為', a[:])
print('a[:5]為', a[:5])
print('a[5:]為', a[5:])
print('a[:-5]為', a[:-5])
print('a[-5:]為', a[-5:])
print('a[0:4]為', a[0:4])
print('a[-5:-3]為', a[-5:-3])
print('a[1:10:3]為', a[1:10:3])
print('a[-1:-4:-1]為', a[-1:-4:-1])
print('a[::-1]為', a[::-1])

shoplist = ['牛奶', '蛋', '咖啡豆', '西瓜', '鳳梨']
shoplist.append('麵包')
print("執行 shoplist.append('麵包')後")
print(shoplist)

shoplist = ['牛奶', '蛋', '咖啡豆', '西瓜', '鳳梨']
shoplist.insert(4, '蘋果')
print("執行 shoplist.insert(4, '蘋果') 後")
print(shoplist)

shoplist = ['牛奶', '蛋', '咖啡豆', '西瓜', '鳳梨']
shoplist.remove('蛋')
print("執行 shoplist.remove('蛋') 後")
print(shoplist)

shoplist = ['牛奶', '蛋', '咖啡豆', '西瓜', '鳳梨']
shoplist.pop(0)
print("執行 shoplist.pop(0) 後")
print(shoplist)
shoplist.pop()
print("執行 shoplist.pop() 後")
print(shoplist)
shoplist.pop(-1)
print("執行 shoplist.pop(-1) 後")
print(shoplist)

shoplist = ['牛奶', '蛋', '咖啡豆', '西瓜', '鳳梨']
del shoplist[0]
print("執行 del shoplist[0] 後")
print(shoplist)

shoplist = ['牛奶', '蛋', '咖啡豆', '西瓜', '鳳梨']
shoplist.sort()
print("執行 shoplist.sort() 後")
print(shoplist)
shoplist = ['milk', 'egg', 'coffee', 'watermelon']
shoplist.sort()
print("執行 shoplist.sort() 後")
print(shoplist)
shoplist.sort(reverse=True)
print("執行 shoplist.sort(reverse=True) 後")
print(shoplist)

list1 = [1, 2, 3, 4]
list2 = list1
print('list1=', list1)
print('list2=', list2)
list1[2]=19
print('list1=', list1)
print('list2=', list2)
list2[2]=18
print('list1=', list1)
print('list2=', list2)

list1 = [1, 2, 3, 4]
list4 = list1.copy()
print('list1 = ', list1)
print('list4 = ', list4)
list4[2] = 19
print('list1=', list1)
print('list4=', list4)

dict1={}
print(dict1)
lang={'早安':'Good Morning', '你好':'Hello'}
print(lang)

a=[['早安','Good Morning'],['你好','Hello']]
dict1 = dict(a)
print(dict1)
b=[('早安','Good Morning'),('你好','Hello')]
dict2 = dict(b)
print(dict2)
c=(['早安','Good Morning'],['你好','Hello'])
dict3 = dict(c)
print(dict3)
d=(('早安','Good Morning'),('你好','Hello'))
dict4 = dict(d)
print(dict4)

