# -*- coding: utf-8 -*-
"""while.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ohnCRy2NHchB8i-C6UR21ihQsmGHX9sN
"""

x = 5
if x < 10:
    print("x小於10!")
x = 5 
while x < 10: 
    print("x小於10!")

x = 5
while x < 10: 
   print("x小於10!")
   print("我還在迴圈中!!") 

x = 5 
while x < 10: 
    print("x小於10!")
    print("我要出迴圈!!")
    x = 100 #變更條件
    print("我出來了")

x = 5 
while x < 10: 
    print("x小於10!")
    print("我要出迴圈!!")
    x = x + 1 
    print("我出來了")

x = 1
while x < 5 :
    print("變數x是", x)
    x = x + 1
    print("Finished")

x = 0 
while x < 10: 
    x = x + 1 
    print("This is",x, "times hello")

x = 0 
while x < 10: 
    print("hello")
    x = x + 1

x = 0
sum = 0

while x < 10
    x = x + 1
    sum =sum + x
    print("Sum is",sum)
print("finished")

sum = 0 
x = 1
while x < 11: 
sum = sum + x 
x = x + 2
print("1 + 3 + 5 + 7 + 9 = ", sum)

sum = 0
i = 0
while sum <= 1000:
i += 1
sum += i*i
print('最小的n值為', i)