# -*- coding: utf-8 -*-
"""while.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hyjoI3zk1OX00LNyQlz59i12Fmp07Bf2
"""

sum = 0

for x in range(1, 11, 2):
   sum = sum + x
   
print("1+3+5+7+9=", sum)

for a in range(6):
   print(a, end=" ")
   
print("")

for b in range(1, 6, 2):
   print(b, end=" ")

print("")

for c in range(2, 6):
   print(c, end=" ")
   
print("")

for d in range(6, 1, -2):
   print(d, end=" ")
   
print("")

n = int(input('請輸入n值?'))
sum = 0;
for i in range(1,n+1):
   sum = sum + i*i;
print(sum)

a = int(input("請輸入第1個數字:"))
b = int(input("請輸入第2個數字:"))

for c in range(a, 1, -1):
   if (a % c == 0 and b % c == 0):
       break
print("最大公約數 GCD =", c)

for c in range(a, a * b):
   if (c % a == 0 and c % b == 0):
       break
print("最小公倍數 LCM =", c)