# -*- coding: utf-8 -*-
"""while Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JVryybrVofq8wMgc0a6SJxm7LIRNb7cL
"""

answer = "123"
while True:
    password = input('請輸入帳號?')
    if password == answer:
     print('帳號正確')
     break
else:
    print('登入失敗')

while True:
    acc = input('請輸入帳號?')
    pwd = input('請輸入密碼?')
    if (acc == '123' and pwd == '456'):
       print('帳號與密碼正確')
       break
else:
       print('登入失敗')

password = "456789"
times = 0
while times <= 3:
    answer = input("Enter Your Password: ")
    if answer == password:
       print("登入成功")
       break
else:
    times = times + 1
    chance = 3 - times
    print("密碼錯誤!還有", chance, "次機會")